// <auto-generated />
using System;
using Catalog.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Entity.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(7934),
                            Name = "Category 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(7951),
                            Name = "Category 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(7952),
                            Name = "Category 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(7954),
                            Name = "Category 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(7954),
                            Name = "Category 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(7957),
                            Name = "Category 6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(7959),
                            Name = "Category 7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(7960),
                            Name = "Category 8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(7961),
                            Name = "Category 9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(7963),
                            Name = "Category 10"
                        });
                });

            modelBuilder.Entity("Catalog.Entity.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8121),
                            Name = "Product 1",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8125),
                            Name = "Product 2",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8126),
                            Name = "Product 3",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8127),
                            Name = "Product 4",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8128),
                            Name = "Product 5",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8130),
                            Name = "Product 6",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8132),
                            Name = "Product 7",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8133),
                            Name = "Product 8",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8134),
                            Name = "Product 9",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8136),
                            Name = "Product 10",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8137),
                            Name = "Product 11",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8138),
                            Name = "Product 12",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8139),
                            Name = "Product 13",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8140),
                            Name = "Product 14",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8141),
                            Name = "Product 15",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8142),
                            Name = "Product 16",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8143),
                            Name = "Product 17",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8183),
                            Name = "Product 18",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8184),
                            Name = "Product 19",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8185),
                            Name = "Product 20",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8186),
                            Name = "Product 21",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8187),
                            Name = "Product 22",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8188),
                            Name = "Product 23",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8189),
                            Name = "Product 24",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8191),
                            Name = "Product 25",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8192),
                            Name = "Product 26",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8193),
                            Name = "Product 27",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8194),
                            Name = "Product 28",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8195),
                            Name = "Product 29",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8196),
                            Name = "Product 30",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8197),
                            Name = "Product 31",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8199),
                            Name = "Product 32",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8200),
                            Name = "Product 33",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8202),
                            Name = "Product 34",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8203),
                            Name = "Product 35",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8204),
                            Name = "Product 36",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8205),
                            Name = "Product 37",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8206),
                            Name = "Product 38",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8207),
                            Name = "Product 39",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8208),
                            Name = "Product 40",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8209),
                            Name = "Product 41",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8210),
                            Name = "Product 42",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8212),
                            Name = "Product 43",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8213),
                            Name = "Product 44",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8214),
                            Name = "Product 45",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8215),
                            Name = "Product 46",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8216),
                            Name = "Product 47",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8217),
                            Name = "Product 48",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8218),
                            Name = "Product 49",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8219),
                            Name = "Product 50",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8220),
                            Name = "Product 51",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8221),
                            Name = "Product 52",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8223),
                            Name = "Product 53",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8224),
                            Name = "Product 54",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8225),
                            Name = "Product 55",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8226),
                            Name = "Product 56",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8227),
                            Name = "Product 57",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8228),
                            Name = "Product 58",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8229),
                            Name = "Product 59",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8230),
                            Name = "Product 60",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8231),
                            Name = "Product 61",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8232),
                            Name = "Product 62",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8233),
                            Name = "Product 63",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8234),
                            Name = "Product 64",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8235),
                            Name = "Product 65",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8275),
                            Name = "Product 66",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8276),
                            Name = "Product 67",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8277),
                            Name = "Product 68",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8278),
                            Name = "Product 69",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8279),
                            Name = "Product 70",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8280),
                            Name = "Product 71",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8281),
                            Name = "Product 72",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8282),
                            Name = "Product 73",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8283),
                            Name = "Product 74",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8284),
                            Name = "Product 75",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8285),
                            Name = "Product 76",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8287),
                            Name = "Product 77",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8288),
                            Name = "Product 78",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8289),
                            Name = "Product 79",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8290),
                            Name = "Product 80",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8291),
                            Name = "Product 81",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8292),
                            Name = "Product 82",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8293),
                            Name = "Product 83",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8294),
                            Name = "Product 84",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8295),
                            Name = "Product 85",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8296),
                            Name = "Product 86",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8297),
                            Name = "Product 87",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8298),
                            Name = "Product 88",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8299),
                            Name = "Product 89",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8300),
                            Name = "Product 90",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8301),
                            Name = "Product 91",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8302),
                            Name = "Product 92",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8303),
                            Name = "Product 93",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8304),
                            Name = "Product 94",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8305),
                            Name = "Product 95",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8306),
                            Name = "Product 96",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8307),
                            Name = "Product 97",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8308),
                            Name = "Product 98",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8309),
                            Name = "Product 99",
                            Price = 10.50m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 6, 19, 14, 37, 59, 637, DateTimeKind.Local).AddTicks(8311),
                            Name = "Product 100",
                            Price = 10.50m,
                            Stock = 1000
                        });
                });

            modelBuilder.Entity("Catalog.Entity.Models.Product", b =>
                {
                    b.HasOne("Catalog.Entity.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Catalog.Entity.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
